apiVersion: v1
kind: Service
metadata:
  name: chaas-kubewol-tcp
  namespace: chaas-frontend
spec:
  ports:
  - name: chaas-kubewol-tcp
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: chaas-kubewol
    env: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaas-kubewol
  namespace: chaas-frontend
spec:
  selector:
    matchLabels:
      app: chaas-kubewol
      env: frontend
  template:
    metadata:
      labels:
        app: chaas-kubewol
        env: frontend
    spec:
      volumes:
        - name: chaas-frontend-kubewol
          persistentVolumeClaim:
            claimName: chaas-frontend-kubewol
      containers:
      - name: kubewol
        image: fchivite/kubewol:latest
        ports:
        - name: kubewol
          containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: chaas-frontend-kubewol
          mountPath: "/kubewol/instance"
